theme: theme-long-teng
baseURL: / 
defaultContentLanguage: en
title: Yieh Corp
description: MDFriday homepage, showcase the product or service.

# Multilingual Configuration
languages:
  en:
    title: Yieh Corp International (English)
    languageName: English
    weight: 1
    contentDir: content/en
  es:
    title: Yieh Corp Internacional (Español)
    languageName: Español
    weight: 2
    contentDir: content/es
  zh:
    title: 燁貿國際股份有限公司 (中文)
    languageName: Chinese
    weight: 3
    contentDir: content/zh

module:
  imports:
    - path: github.com/mdfriday/theme-long-teng

params:
  Author: william_Cruz
  internalLinkTarget: _self
