theme: theme-long-teng
baseURL: / 
defaultContentLanguage: en
title: Company X
description: MDFriday homepage, showcase the product or service.

# Multilingual Configuration
languages:
  en:
    title: Company X (English)
    languageName: English
    weight: 1
    contentDir: content/en
  es:
    title: Company X (Español)
    languageName: Español
    weight: 2
    contentDir: content/es
  zh:
    title: 公司X (中文)
    languageName: Chinese
    weight: 3
    contentDir: content/zh
  ja:
    title: 会社X (日本語)
    languageName: Japanese
    weight: 4
    contentDir: content/ja
  ko:
    title: Company X
    languageName: Korean
    weight: 5
    contentDir: content/ko
  th:
    title: Company Xัด (ไทย)
    languageName: Thai
    weight: 6
    contentDir: content/th
  vi:
    title: Company X
    languageName: Vietnamese
    weight: 7
    contentDir: content/vi

module:
  imports:
    - path: github.com/mdfriday/theme-long-teng

params:
  Author: william_Cruz
  internalLinkTarget: _self
  
markup:
  goldmark:
    renderer:
      unsafe: true
