[build]
command = 'hugo'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.140.1'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'

[params]
# Add this for internal links
internalLinkTarget = "_self" 

[[redirects]]
  from = "/contact"
  to = "/en/thank-you"
  status = 302
  force = true

[[redirects]]
  from = "/es/contact"
  to = "/es/thank-you"
  status = 302
  force = true
  
[[redirects]]
  from = "/zh/contact"
  to = "/zh/thank-you"
  status = 302
  force = true

[[redirects]]
  from = "/ja/contact"
  to = "/ja/thank-you"
  status = 302
  force = true

[[redirects]]
  from = "/ko/contact"
  to = "/ko/thank-you"
  status = 302
  force = true
  
[[redirects]]
  from = "/th/contact"
  to = "/th/thank-you"
  status = 302
  force = true

[[redirects]]
  from = "/vi/contact"
  to = "/vi/thank-you"
  status = 302
  force = true